<?php
include_once "../model/chamado.php";
include_once "../model/chamadoDAO.php";
include_once "../model/prioridade.php";
include_once "../model/prioridadeDAO.php";
include_once "../model/categoria.php";
include_once "../model/categoriaDAO.php";
include_once "../model/status.php";
include_once "../model/statusDAO.php";
include_once "../model/usuario.php";
include_once "../model/usuarioDAO.php";
$codChamado = $_REQUEST["cod_chamado"];
$nome = $_REQUEST["nome"];
$descricao = $_REQUEST["descricao"];
$horario = $_REQUEST["horario"];
$data = $_REQUEST["data"];
$prioridade = $_REQUEST["prioridade"];
$categoria = $_REQUEST["categoria"];
$status = $_REQUEST["status"];
$usuario = $_REQUEST["usuario"];
$chamado = new Chamado();
$chamado->setCodChamado($codChamado);
$chamado->setNome($nome);
$chamado->setDescricao($descricao);
$chamado->setHorario($horario);
$chamado->setData($data);
$p = new Prioridade();
$p->setIdPrioridade($prioridade);
$chamado->setfkIdPrioridade($p);
$cat = new Categoria();
$cat->setIdCategoria($categoria);
$chamado->setfkIdCategoria($cat);
$s = new Status();
$s->setIdStatus($status);
$chamado->setfkIdStatus($s);
$u = new Usuario();
$u->setIdUsuario($usuario);
$chamado->setfkIdUsuario($u);
$cDao = new ChamadoDAO();
$cDao->alterar($chamado);
header("Location: ../view/form_listar_chamado.php");
?>
