<?php
include_once "../model/conexao.php";
include_once "../model/usuarioDAO.php";
include_once "../model/usuario.php";
include_once "../model/prioridade.php";
include_once "../model/prioridadeDAO.php";
include_once "../model/categoria.php";
include_once "../model/categoriaDAO.php";
include_once "../model/status.php";
include_once "../model/statusDAO.php";
include_once "../model/chamado.php";
include_once "../model/chamadoDAO.php";
$nome = $_POST["nome"];
$descricao = $_POST["descricao"];
$prioridade = $_POST["prioridade"];
$categoria = $_POST["categoria"];
$status = $_POST["status"];
$usuario= $_POST["usuario"];
$horario= $_POST["horario"];
$data= $_POST["data"];
$chamado = new Chamado();
$chamado->setNome($nome);
$chamado->setDescricao($descricao);
$chamado->setHorario($horario);
$chamado->setData($data);
$p = new Prioridade();
$p->setIdPrioridade($prioridade);
$chamado->setfkIdPrioridade($p);
$cat = new Categoria();
$cat->setIdCategoria($categoria);
$chamado->setfkIdCategoria($cat);
$s = new Status();
$s->setIdStatus($status);
$chamado->setfkIdStatus($s);
$u = new Usuario();
$u->setIdUsuario($usuario);
$chamado->setfkIdUsuario($u);
$chamadoDAO = new ChamadoDAO();
$chamadoDAO->inserir($chamado);
header("Location: ../view/form_listar_chamado.php");
?>